apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-nginx-app
  template:
    metadata:
      labels:
        app: react-nginx-app
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: react-nginx-app
          image: skillhub.azurecr.io/react-nginx-app:latest
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  namespace: nginx
  name: nginx-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: react-nginx-app
  type: LoadBalancer
